apiVersion: v1
kind: Service
metadata:
 name: worker-service
 labels:
   name: worker-service
   app: demo-voting-app
spec:
    selector:
        name: worker-app-pod
        app: demo-voting-app